# Default values for kagent
replicaCount: 1

global:
  tag: ""

tools:
  loglevel: "debug"
  image:
    registry: ghcr.io
    repository: kagent-dev/kagent/tools
    tag: ""
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  prometheus:
    url: "prometheus.kagent.svc.cluster.local:9090"
    username: ""
    password: ""
  grafana: # kubectl port-forward svc/grafana 3000:3000
    url: "http://grafana.kagent.svc.cluster.local:3000"
    apiKey: ""

service:
  type: ClusterIP
  ports:
    tools:
      port: 8084
      targetPort: 8084
      nodePort:  # Only used if service.type is NodePort

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

otel:
  tracing:
    enabled: false
    exporter:
      otlp:
        endpoint: http://host.docker.internal:4317
        timeout: 15
        insecure: true

# MongoDB configuration
mongodb:
  enabled: true
  uri: "mongodb://kagent:kagent-mongodb-password@mongodb.kagent.svc.cluster.local:27017/kagent-alerts?authSource=kagent-alerts"

# Proxy configuration
proxy:
  http: "http://hpeproxy.its.hpecorp.net:80"
  https: "http://hpeproxy.its.hpecorp.net:80"
  noProxy: "m2-lr1-dev-vm215224.mip.storage.hpecorp.net,10.96.0.1,10.96.0.0/12,10.96.0.12,10.244.0.0/16,.external.hpe.local,localhost,.cluster.local,.svc,.default.svc,127.0.0.1,172.25.0.2,172.25.0.3,172.25.0.4,172.25.0.5,172.25.0.6,172.25.0.7,172.25.0.8,172.25.0.9,172.25.0.0/8,10.227.215.223,172.25.0.24,172.25.0.27,0.0.0.0"
